version: "3.8"

services:

  keycloak:
    build:
      context: .
      dockerfile: Dev.Dockerfile
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password

