version: "3.8"

services:

  keycloak:
    build: .
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      MAILCHIMP_API_KEY: one
      MAILCHIMP_LIST_ID: two
