version: "3.8"

services:

  keycloak:
    build:
      context: .
      dockerfile: Dev.Dockerfile
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      MAILCHIMP_API_KEY: one-second
      MAILCHIMP_LIST_ID: two
      MAILCHIMP_LISTENED_EVENT_LIST: LOGIN,REGISTER,CLIENT_LOGIN
